name: dsbmobile_api
description: A DSBMobile API wrapper library for Dart.
version: 1.0.0
homepage: https://github.com/spnda/dsbmobile_api

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  http: ^0.13.3
  uuid: ^3.0.4
  intl: ^0.17.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.11.1
